"""empty message

Revision ID: 120d0869bddd
Revises: 6b7fc2ccd088
Create Date: 2020-05-26 17:44:58.064315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120d0869bddd'
down_revision = '6b7fc2ccd088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('artefacts', sa.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('task', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('role', sa.String(length=100), nullable=True))
    op.add_column('task', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('task', sa.Column('user_email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'user_email')
    op.drop_column('task', 'state')
    op.drop_column('task', 'role')
    op.drop_column('task', 'deadline')
    op.drop_column('task', 'created')
    op.drop_column('task', 'artefacts')
    # ### end Alembic commands ###
