"""empty message

Revision ID: 15dfe24ad38c
Revises: 92fdc020b391
Create Date: 2020-05-13 05:30:02.163578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15dfe24ad38c'
down_revision = '92fdc020b391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'created_by')
    # ### end Alembic commands ###
