"""empty message

Revision ID: 6b7fc2ccd088
Revises: 15dfe24ad38c
Create Date: 2020-05-22 10:11:14.100759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7fc2ccd088'
down_revision = '15dfe24ad38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='project_users_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='project_users_user_id_fkey')
    )
    # ### end Alembic commands ###
