"""empty message

Revision ID: 83749f93fc65
Revises: 2833870330ef
Create Date: 2020-05-26 19:09:03.055031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83749f93fc65'
down_revision = '2833870330ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('artefacts', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'artefacts')
    # ### end Alembic commands ###
