"""empty message

Revision ID: 876f52fabb2a
Revises: 
Create Date: 2020-05-07 18:59:40.363521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876f52fabb2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=100), nullable=True))
    op.drop_constraint('user_login_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_login_key', 'user', ['login'])
    op.drop_column('user', 'email')
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
