"""empty message

Revision ID: 92fdc020b391
Revises: eb0d8f085fb2
Create Date: 2020-05-13 05:12:58.876706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92fdc020b391'
down_revision = 'eb0d8f085fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
