"""empty message

Revision ID: dd80f3a92ea4
Revises: 120d0869bddd
Create Date: 2020-05-26 18:59:27.005673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd80f3a92ea4'
down_revision = '120d0869bddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_title_key', 'task', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('task_title_key', 'task', ['title'])
    # ### end Alembic commands ###
