"""empty message

Revision ID: eb0d8f085fb2
Revises: 876f52fabb2a
Create Date: 2020-05-13 04:34:53.904870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0d8f085fb2'
down_revision = '876f52fabb2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('project', sa.Column('quantity_participants', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('slug', sa.String(length=140), nullable=True))
    op.create_unique_constraint(None, 'project', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'slug')
    op.drop_column('project', 'quantity_participants')
    op.drop_column('project', 'created_by')
    op.drop_column('project', 'created')
    # ### end Alembic commands ###
