"""empty message

Revision ID: fb0e40f80162
Revises: 83749f93fc65
Create Date: 2020-05-26 20:53:22.445257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0e40f80162'
down_revision = '83749f93fc65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('slug', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'slug')
    # ### end Alembic commands ###
